#!/bin/sh
set -eu

COLLECTOR_PUBLISHER="${COLLECTOR_PUBLISHER:-echo}"
COLLECTOR_THERMAL="${COLLECTOR_THERMAL:-true}"
COLLECTOR_THERMAL_ROOT="${COLLECTOR_THERMAL_ROOT:-/sys/devices/virtual/thermal}"
COLLECTOR_THERMAL_ZONE="${COLLECTOR_THERMAL_ZONE:-true}"
COLLECTOR_THERMAL_TYPE="${COLLECTOR_THERMAL_TYPE:-false}"

thermal_publish() {
  "${COLLECTOR_PUBLISHER}" 'thermal' "${@}"
}

thermal_collect() {
  if [ "${COLLECTOR_THERMAL}" != 'true' ]; then
    return;
  fi
  find "${COLLECTOR_THERMAL_ROOT}" -name 'thermal_zone*' | sort | while read -r device; do
    temp="$(sed -E 's/([0-9]{2})([0-9]+)/\1.\2/' <"${device}/temp")"
    if [ "${COLLECTOR_THERMAL_ZONE}" ]; then
      zone="$(basename "${device}")"
      thermal_publish "${zone}" 'temperature' "${temp} °C"
    fi
    if [ "${COLLECTOR_THERMAL_TYPE}" ]; then
      type="$(cat "${device}/type")"
      thermal_publish "${type}" 'temperature' "${temp} °C"
    fi
  done
}

thermal_collect
