#!/bin/sh
set -eu

COLLECTOR_PUBLISHER="${COLLECTOR_PUBLISHER:-echo}"
COLLECTOR_THERMAL="${COLLECTOR_THERMAL:-true}"
COLLECTOR_THERMAL_ROOT="${COLLECTOR_THERMAL_ROOT:-/sys/devices/virtual/thermal}"

thermal_publish() {
  "${COLLECTOR_PUBLISHER}" 'thermal' "${@}"
}

thermal_collect() {
  if [ "${COLLECTOR_THERMAL}" != 'true' ]; then
    return;
  fi
  find "${COLLECTOR_THERMAL_ROOT}" -name 'thermal_zone*' | sort | while read -r device; do
    zone="$(basename "${device}")"
    temp="$(sed -E 's/([0-9]{2})([0-9]+)/\1.\2/' <"${device}/temp")"
    thermal_publish "${zone}" 'temperature' "${temp} °C"
  done
}

thermal_collect
